name: CI

on:
  pull_request:
    branches: [ master ]

  workflow_dispatch:
    inputs:
      version:
        description: 'Release version to create'     
        required: true

jobs:
  build_and_test:
    strategy:
      matrix:
        include:
          - vm: windows-latest
    runs-on: ${{ matrix.vm }}
    name: Build and test ${{ matrix.vm }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup dotnet
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0.x'
          include-prerelease: true
      - name: Setup zig
        if: ${{ github.event.inputs.version == '' }}
        uses: goto-bus-stop/setup-zig@v2
      - name: Build (CI)
        if: ${{ github.event.inputs.version == '' }}
        run: |
          dotnet build -t:Pack src/PublishAotCross.nuproj
          dotnet publish -r linux-x64 -c Release test/Hello.csproj -p:StripSymbols=false
      - name: Upload test binary
        if: ${{ github.event.inputs.version == '' }}
        uses: actions/upload-artifact@v2
        with:
          name: Hello
          path: src/bin/Release/net8.0/linux-x64/publish/Hello
      - name: Build (CD)
        if: ${{ github.event.inputs.version != '' }}
        run: dotnet build -t:Pack src/PublishAotCross.nuproj -p:Version=${{ github.event.inputs.version }}
      - name: Archive NuGet
        if: ${{ github.event.inputs.version != '' }}
        uses: actions/upload-artifact@v2
        with:
          name: PublishAotCross.${{ github.event.inputs.version }}.nupkg
          path: src/bin/Debug/PublishAotCross.${{ github.event.inputs.version }}.nupkg
      - name: Create tag
        if: ${{ github.event.inputs.version != '' && github.actor == 'MichalStrehovsky' }}
        run: |
          git tag v${{ github.event.inputs.version }}
          git push origin v${{ github.event.inputs.version }}
